### ISSUE TITLE
Rename projects and folders to not include "Doctrina."

### ISSUE THREAD

**Issue by rasmuseeg** [bitflipping-net/doctrina-lrs#10]
- [ ] Rename *.csproj to not include Doctrina
- [ ] Add csproj RootNamespace property of `Doctrina.WebUI` etc.
- [ ] Rename folder `Doctrina.*` without `Doctrina.` eg. `Doctrina.WebUI` -> `WebUI`
- [ ] Update path within `Infrastucture` design factory.
- [ ] Update `build.ps1`

**Comment by benichka** [comment]
I can be on it if that is no problem.

**Comment by rasmuseeg** [comment]
Thank you, please do so. 
Though please base it on the feature/dotnetcore-3.0 branch Thanks 👍

**Comment by rasmuseeg** [comment]
Hi, I've merged the `feature/dotnetcore-3.0` branch into develop. Please go-a-head and use that branch now :-)

**Comment by benichka** [comment]
Thanks, will do!
