### ISSUE TITLE
[git submodule] does not restore (src\experience-api) repository.

### ISSUE THREAD

**Issue by AdvikJadhav1990** [bitflipping-net/doctrina-lrs#11]
Hi,

I tried to set up afresh but facing the same kind of issues. [git submodule], [git submodule update] command can restore (lrs-conformance-test-suite @ 14778f9) but could not restore (src\experience-api @ 0551e7d).

Can you please fix the same...

![image](https://user-images.githubusercontent.com/56162817/66454870-c994cc00-ea86-11e9-94ac-ebe1aa2d635b.png)

**Comment by rasmuseeg** [comment]
Have you tried doing a fresh clone?

**Comment by AdvikJadhav1990** [comment]
Thanks for quick response.

Yes Rasmus, I tried afresh now only...



Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by rasmuseeg** [comment]
So sorry, i had a commit change laying around locally on experience-api submodule. Please try and run `git submodule update` again.

**Comment by AdvikJadhav1990** [comment]
Ok Thanks, let me try...


Sent from Outlook<http://aka.ms/weboutlook>
________________________________
