### ISSUE TITLE
Probably needs Prerequisites update

### ISSUE THREAD

**Issue by benichka** [bitflipping-net/doctrina-lrs#15]
Hello @rasmuseeg,
I cloned the repo to test it and see if I can help for some open issues :slightly_smiling_face:.
Doing this, I faced a problem on VS2017: the SDK for .NET Core 2.2 needs to be specific versions for VS2017 and for VS2019; otherwise, VS doesn't recognised the v2.2 of .NET Core and refuse to build the solution.

Is it OK to create a pull request to update the readme about it?

Also, it might be good to add NodeJS and Docker as a requirement; what do you think?

Thanks!

Links that explain the problem:
https://developercommunity.visualstudio.com/content/problem/470616/the-current-net-sdk-does-not-support-targeting-net-5.html
https://github.com/dotnet/announcements/issues/108

**Comment by rasmuseeg** [comment]
Hello @benichka ,
Thanks for showing your interest! Any help is much appreciated. :-)
I did recently create a new branch located here: [feature/dotnetcore-30.0](https://github.com/bitflipping-net/doctrina-lrs/tree/feature/dotnetcore-3.0)

This branch is about to get merged soon, as it fixes several issues with both docker and ef-core.
And also updates the projects to `netcoreapp3.0` which does not appear to have that problem.
Could you try the linked branch and see if you experience the same problems?
Thank you! 👍

**Comment by rasmuseeg** [comment]
Hello @benichka,

I've update the develop branch to use `netcoreapp3.0` which does not have those issues. Please try develop branch, and report back with your experience getting started :-)

**Comment by benichka** [comment]
Hello,
indeed the .NET Core 3 simplifies thing as only VS 2019 can handle it 😄.

Now, using VS2019, I am able to run it, though I can't seem to be able to log because of a 404 error:
![login fail](https://user-images.githubusercontent.com/26501529/66783712-cb242100-eed8-11e9-8f58-a3fd1fe83885.png)

Not sure it should fail at this point or if I should be able to login with admin@example.com/zKR4gkYNHP5tvH?

Also, please note that I'm a total newbie regarding TypeScript, NodeJS, React and Docker. I'll be glad to learn while helping but if you need someone already skilled on it I'm afraid I won't fit!

**Comment by rasmuseeg** [comment]
I removed the login controller for now, and I'm not quite sure I want to use react.
Perhaps I'll separate the frontend into its own project later on.
Because I think I would rather change to razor pages with a mix of blazor for SPA.


This means that the login won't work. There wasn't anything on the other side anyways :-)

You should try hitting the /xapi/about endpoint. Perhaps even try running the Conformance Test suite against that endpoint.

Regarding your skill level, any help is much appreciated. No worries there :-)


________________________________

**Comment by rasmuseeg** [comment]
I'll close this issue because it is no longer relevant.

**Comment by benichka** [comment]
Sure.
Sorry I've not been very active; I have some very dense days lately.
Plus I have some trouble getting the app to run, something to do with certificates only when running the container. I'll detail my trouble in another topic :).
