### ISSUE TITLE
[git submodule] does not restore anything...

### ISSUE THREAD

**Issue by AdvikJadhav1990** [bitflipping-net/doctrina-lrs#3]

**Comment by rasmuseeg** [comment]
The Setup section of the readme.md has been updated with the following:
**Setup**
Follow these steps to get your development environment set up:

1. Clone the repository
2. Initialize submodule in the local configuration
git submodule init
3. Fetch all data for each submodule
git submodule update

Use these instruction, and is should work as intended.
